import { useEffect, useMemo, useRef, useState } from 'react';
import { MessageCircle, ShieldAlert, Moon, Sun, LogOut, Phone, Info, MoreHorizontal, Paperclip, Smile, Send, AlertTriangle, CheckCheck, Link as LinkIcon, Search, ArrowLeft, Plus, RefreshCw, Trash2, X } from 'lucide-react';
import './App.css';
import { checkPhone, deleteConversation, getConversations, getMessages, getSpamMessages, loginWithPhone, markConversationRead, sendMessage } from './services/smsService';

const avatar = (name, bg = '007AFF') => `https://ui-avatars.com/api/?name=${encodeURIComponent(name || 'Unknown')}&background=${bg}&color=fff&bold=true`;
const riskLabel = (severity) => ({ high: 'High Risk', medium: 'Medium Risk', low: 'Low Risk' }[severity] || 'Medium Risk');
const formatTime = (value) => value ? new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : '';
const dayLabel = (value) => {
  const d = new Date(value); if (Number.isNaN(d.getTime())) return ''; const now = new Date();
  const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const target = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const diff = Math.round((start - target) / 86400000); if (diff === 0) return 'Today'; if (diff === 1) return 'Yesterday'; return d.toLocaleDateString([], { weekday: 'long' });
};

function SwipeRow({ children, onDelete }) {
  const [dx, setDx] = useState(0); const startX = useRef(0); const dragging = useRef(false);
  const onDown = (e) => { dragging.current = true; startX.current = e.clientX ?? e.touches?.[0]?.clientX ?? 0; };
  const onMove = (e) => { if (!dragging.current) return; const x = e.clientX ?? e.touches?.[0]?.clientX ?? 0; const next = Math.min(0, Math.max(-92, x - startX.current)); setDx(next); };
  const onUp = () => { if (!dragging.current) return; dragging.current = false; setDx(dx < -56 ? -92 : 0); };
  return <div className="swipe-wrap"><button className="delete-reveal" onClick={onDelete}><Trash2 size={16}/>Delete</button><div className="swipe-card" style={{ transform: `translateX(${dx}px)` }} onMouseDown={onDown} onMouseMove={onMove} onMouseUp={onUp} onMouseLeave={onUp} onTouchStart={onDown} onTouchMove={onMove} onTouchEnd={onUp}>{children}</div></div>;
}

function Sidebar({ page, setPage, dark, setDark, user, spamCount, onLogout }) {
  const items = [['chat-list', 'Chats', MessageCircle], ['spam-list', 'Spam', ShieldAlert, spamCount, 'red']];
  return <aside className="sidebar"><div className="brand"><div className="logo"><MessageCircle size={22}/></div><span>SMS Shield</span></div><nav>{items.map(([id, label, Icon, badge, tone]) => <button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => setPage(id)}><Icon size={19}/><span>{label}</span>{badge ? <b className={`badge ${tone}`}>{badge}</b> : null}</button>)}</nav><div className="sidebar-bottom"><div className="mini-actions"><button className="mini-icon" onClick={() => setDark(!dark)} title="Toggle theme">{dark ? <Sun size={16}/> : <Moon size={16}/>}</button><button className="mini-icon" onClick={onLogout} title="Logout"><LogOut size={16}/></button></div><div className="profile-card"><img src={avatar(user.full_name || user.fullName)}/><div><strong>{user.full_name || user.fullName}</strong><small>{user.phone}</small></div></div></div></aside>;
}

function LoginPage({ onCheck, onRegister, loading, error, registerPhone }) {
  const [phone, setPhone] = useState('+62'); const [fullName, setFullName] = useState('');
  if (registerPhone) return <main className="auth-page"><section className="auth-card"><div className="logo auth-logo"><MessageCircle size={24}/></div><h1>Daftar Akun</h1><p>Nomor belum ditemukan. Lengkapi nama untuk membuat akun baru.</p><input value={registerPhone} disabled/><input value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Nama lengkap"/>{error ? <small className="error-text">{error}</small> : null}<button className="primary-cta" onClick={() => onRegister(registerPhone, fullName)} disabled={loading || !fullName.trim()}>{loading ? 'Membuat akun...' : 'Daftar'}</button></section></main>;
  return <main className="auth-page"><section className="auth-card"><div className="logo auth-logo"><MessageCircle size={24}/></div><h1>SMS Shield</h1><p>Masukkan nomor telepon untuk masuk.</p><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="Nomor telepon"/>{error ? <small className="error-text">{error}</small> : null}<button className="primary-cta" onClick={() => onCheck(phone)} disabled={loading || !phone.trim()}>{loading ? 'Memeriksa...' : 'Lanjut'}</button></section></main>;
}

function NewChatModal({ open, onClose, onSubmit, knownExists, warning, sending }) {
  const [phone, setPhone] = useState(''); const [name, setName] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { if (!open) { setPhone(''); setName(''); setMessage(''); } }, [open]);
  if (!open) return null;
  return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><h2>New Chat</h2><button className="mini-icon" onClick={onClose}><X size={16}/></button></div><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="Nomor tujuan"/><input value={name} onChange={e => setName(e.target.value)} placeholder="Nama kontak (opsional)"/><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Isi pesan" />{warning ? <small className="warn-text">Nomor belum ada di daftar chat. Lanjutkan akan membuat chat baru.</small> : null}<button className="primary-cta send-loading-btn" onClick={() => onSubmit({ phone, name, message })} disabled={!phone.trim() || !message.trim() || sending}>{sending ? <><span className="spinner"/>Mengirim...</> : (knownExists ? 'Kirim ke chat' : 'Buat chat baru')}</button></div></div>;
}

function ChatListPage({ items, openChat, refresh, openComposer, removeChat }) {
  return <main className="content-page list-page"><section className="ios-list-panel"><header className="ios-list-header"><h1>Messages</h1><button className="compose-btn" onClick={openComposer}><Plus size={19}/></button></header><div className="search ios-search"><Search size={17}/><input placeholder="Search messages"/></div><div className="conversation-list ios-list">{items.length ? items.map(c => <SwipeRow key={c.id} onDelete={() => removeChat(c.id)}><button className="conversation-card page-card" onClick={() => openChat(c.id, c.is_spam ? 'spam-room' : 'chat-room')}><img src={avatar(c.contact_name, c.is_spam ? 'FF3B30' : '007AFF')}/><div className="conv-main"><div><strong>{c.contact_name}</strong><span>{formatTime(c.last_message_at || c.updated_at)}</span></div><p>{c.last_message || 'No messages yet.'}</p>{c.is_spam ? <div className="spam-meta"><AlertTriangle size={12}/><em>Spam</em><span>{Math.round((Number(c.last_confidence) || 0) * 100)}%</span></div> : null}</div>{Number(c.unread_count) ? <i>{Number(c.unread_count) > 9 ? '9+' : c.unread_count}</i> : null}</button></SwipeRow>) : <div className="empty-state center-empty"><button className="demo-refresh" onClick={refresh}><RefreshCw size={26}/></button><p>No conversations yet.</p></div>}</div></section></main>;
}

function ChatRoomPage({ convo, messages, back, spamMode, onSend }) {
  const [draft, setDraft] = useState('');
  const grouped = useMemo(() => messages.map((m, i) => ({ ...m, day: i === 0 || dayLabel(messages[i - 1].created_at) !== dayLabel(m.created_at) ? dayLabel(m.created_at) : '' })), [messages]);
  const submit = (e) => { e.preventDefault(); if (!draft.trim()) return; onSend(draft); setDraft(''); };
  return <main className="content-page"><header className="chat-room-top"><button className="back-btn" onClick={back}><ArrowLeft size={18}/>Back</button><div className="room-actions"><button className="icon-btn"><Phone size={18}/></button><button className="icon-btn"><Info size={18}/></button><button className="icon-btn"><MoreHorizontal size={18}/></button></div></header><section className="room-shell"><div className="chat-header"><div><img src={avatar(convo.contact_name, convo.is_spam ? 'FF3B30' : '007AFF')}/><div><strong>{convo.contact_name}</strong><small>{convo.contact_phone}</small></div></div>{spamMode && <div className="room-flag"><AlertTriangle size={16}/><span>Spam Conversation</span></div>}</div><div className="messages room-messages">{grouped.length ? grouped.map(m => <div key={m.id}>{m.day && <div className="day-sep">{m.day}</div>}<div className={`bubble-row ${m.direction === 'outgoing' ? 'me' : 'them'}`}><div className={`bubble ${m.type === 'link' ? 'link' : ''}`}>{m.type === 'link' && <LinkIcon size={16}/>} {m.body}</div>{m.status ? <small className="status"><CheckCheck size={13}/>{m.status}</small> : null}</div></div>) : <div className="empty-state">No messages in this chat.</div>}</div>{!spamMode && <form className="composer" onSubmit={submit}><button type="button"><Paperclip size={19}/></button><input value={draft} onChange={e => setDraft(e.target.value)} placeholder="Type a message"/><button type="button"><Smile size={19}/></button><button type="submit" className="send"><Send size={18}/></button></form>}</section></main>;
}

function SpamListPage({ items, openSpam, refresh, removeChat }) {
  return <main className="content-page list-page"><section className="ios-list-panel"><header className="ios-list-header"><h1>Spam Messages</h1><b className="badge red large">{items.length}</b></header><div className="search ios-search"><Search size={17}/><input placeholder="Search spam"/></div><div className="conversation-list ios-list">{items.length ? items.map(c => <SwipeRow key={c.message_id || c.id} onDelete={() => removeChat(c.conversation_id)}><button className="conversation-card page-card spam-row" onClick={() => openSpam(c.conversation_id, 'spam-detail')}><img src={avatar(c.contact_name || c.contact_phone, 'FF3B30')}/><div className="conv-main"><div><strong>{c.contact_name || c.contact_phone}</strong><span>{formatTime(c.created_at)}</span></div><p>{c.body}</p><div className="spam-meta"><AlertTriangle size={12}/><em>{riskLabel(c.severity)}</em><span>{Math.round((Number(c.confidence) || 0) * 100)}%</span></div></div></button></SwipeRow>) : <div className="empty-state center-empty"><button className="demo-refresh" onClick={refresh}><RefreshCw size={26}/></button><p>No spam detected.</p></div>}</div></section></main>;
}

function SpamDetailPage({ convo, item, messages, back, openRoom }) {
  const meta = item ? JSON.parse(item.explanation || '{}') : {};
  return <main className="content-page"><header className="chat-room-top"><button className="back-btn" onClick={back}><ArrowLeft size={18}/>Back</button><button className="primary-cta slim" onClick={() => openRoom(convo.id, 'spam-room')}>Open Spam Chat</button></header><div className="detail-layout"><section className="analysis detail-card"><div className="analysis-head"><img src={avatar(convo.contact_name, 'FF3B30')}/><b className="badge red">Spam</b></div><h3>{convo.contact_phone}</h3><p>{item?.country || 'Unknown'} • {item?.carrier || 'Unknown'}</p><blockquote>{item?.body || convo.last_message}</blockquote><div className="score"><span>Spam confidence</span><b>{Math.round((Number(item?.confidence) || 0) * 100)}%</b></div><div className="bar"><i style={{ width: `${Math.round((Number(item?.confidence) || 0) * 100)}%` }} /></div><div className="explain"><h4>Detection Explanation</h4>{(meta.indicators || ['Model classified this SMS as spam']).map(x => <span key={x}>{x}</span>)}{(meta.keywords || []).map(x => <span key={x}>Keyword: {x}</span>)}</div></section><section className="thread-preview"><h2>Chat Room Preview</h2><div className="messages embed">{messages.map(m => <div key={m.id}><div className={`bubble-row ${m.direction === 'outgoing' ? 'me' : 'them'}`}><div className={`bubble ${m.type === 'link' ? 'link' : ''}`}>{m.type === 'link' && <LinkIcon size={16}/>} {m.body}</div></div></div>)}</div></section></div></main>;
}

export default function App() {
  const [dark, setDark] = useState(false), [user, setUser] = useState(null), [page, setPage] = useState('chat-list'), [conversations, setConversations] = useState([]), [spamItems, setSpamItems] = useState([]), [messages, setMessages] = useState([]), [activeId, setActiveId] = useState(null), [authLoading, setAuthLoading] = useState(false), [authError, setAuthError] = useState(''), [registerPhone, setRegisterPhone] = useState(''), [composerOpen, setComposerOpen] = useState(false), [composeWarning, setComposeWarning] = useState(false), [sending, setSending] = useState(false), [notice, setNotice] = useState('');
  const activeConversation = useMemo(() => conversations.find(x => Number(x.id) === Number(activeId)) || null, [conversations, activeId]);
  const activeSpam = useMemo(() => spamItems.find(x => Number(x.conversation_id) === Number(activeId)) || null, [spamItems, activeId]);
  const loadConversations = async (phone) => { const [{ items: convos }, { items: spam }] = await Promise.all([getConversations(phone), getSpamMessages(phone)]); setConversations(convos); setSpamItems(spam); if (!activeId && convos[0]) setActiveId(convos[0].id); };
  const loadMessages = async (phone, id) => { if (!id) return setMessages([]); const { items } = await getMessages(phone, id); setMessages(items); };
  const enterUser = async (u) => { setUser(u); localStorage.setItem('sms_user', JSON.stringify(u)); await loadConversations(u.phone); };
  const handlePhoneCheck = async (phone) => { try { setAuthLoading(true); setAuthError(''); const res = await checkPhone(phone); if (res.exists) await enterUser(res.user); else setRegisterPhone(phone); } catch (e) { setAuthError(e.message); } finally { setAuthLoading(false); } };
  const handleRegister = async (phone, fullName) => { try { setAuthLoading(true); setAuthError(''); const { user: u } = await loginWithPhone(phone, fullName); setRegisterPhone(''); await enterUser(u); } catch (e) { setAuthError(e.message); } finally { setAuthLoading(false); } };
  const openChat = async (id, target) => { setActiveId(id); setPage(target); if (user) { await markConversationRead(user.phone, id); await loadConversations(user.phone); await loadMessages(user.phone, id); } };
  const handleSend = async (text) => { if (!user || !activeConversation) return; setSending(true); try { const res = await sendMessage(user.phone, { contact_phone: activeConversation.contact_phone, contact_name: activeConversation.contact_name, message: text, direction: 'outgoing' }); if (res.hidden_from_sender) setNotice('Pesan terdeteksi spam. Pesan hanya tampil di akun tujuan sebagai spam.'); await loadConversations(user.phone); await loadMessages(user.phone, activeConversation.id); } finally { setSending(false); } };
  const handleComposerSubmit = async ({ phone, name, message }) => { if (!user) return; const cleanPhone = phone.trim(); const known = conversations.some(c => c.contact_phone === cleanPhone); setComposeWarning(!known); if (!known && !composeWarning) return; setSending(true); try { const res = await sendMessage(user.phone, { contact_phone: cleanPhone, contact_name: name.trim() || cleanPhone, message: message.trim(), direction: 'outgoing' }); setComposerOpen(false); setComposeWarning(false); if (res.hidden_from_sender) setNotice('Pesan terdeteksi spam. Chat ditandai spam; isi asli hanya masuk ke akun tujuan.'); await loadConversations(user.phone); const { items } = await getConversations(user.phone); const created = items.find(c => c.contact_phone === cleanPhone); if (created) await openChat(created.id, res.hidden_from_sender ? 'spam-room' : 'chat-room'); } finally { setSending(false); } };
  const handleDelete = async (id) => { if (!user) return; await deleteConversation(user.phone, id); if (Number(activeId) === Number(id)) { setActiveId(null); setMessages([]); setPage('chat-list'); } await loadConversations(user.phone); };
  const handleLogout = () => { localStorage.removeItem('sms_user'); setRegisterPhone(''); setUser(null); setConversations([]); setSpamItems([]); setMessages([]); setActiveId(null); setPage('chat-list'); };
  useEffect(() => { const saved = localStorage.getItem('sms_user'); if (saved && !user) { const u = JSON.parse(saved); setUser(u); loadConversations(u.phone); } }, []);
  useEffect(() => { if (user) loadConversations(user.phone); }, [user]);
  if (!user) return <div className={`app single ${dark ? 'dark' : ''}`}><LoginPage onCheck={handlePhoneCheck} onRegister={handleRegister} loading={authLoading} error={authError} registerPhone={registerPhone} /></div>;
  return <div className={`app shell ${dark ? 'dark' : ''}`}><Sidebar page={page} setPage={setPage} dark={dark} setDark={setDark} user={user} spamCount={spamItems.length} onLogout={handleLogout} />{page === 'chat-list' && <ChatListPage items={conversations} openChat={openChat} refresh={() => loadConversations(user.phone)} openComposer={() => { setComposeWarning(false); setComposerOpen(true); }} removeChat={handleDelete} />}{page === 'chat-room' && activeConversation && <ChatRoomPage convo={activeConversation} messages={messages} back={() => setPage('chat-list')} spamMode={false} onSend={handleSend} />}{page === 'spam-list' && <SpamListPage items={spamItems} openSpam={openChat} refresh={() => loadConversations(user.phone)} removeChat={handleDelete} />}{page === 'spam-detail' && activeConversation && <SpamDetailPage convo={activeConversation} item={activeSpam} messages={messages} back={() => setPage('spam-list')} openRoom={openChat} />}{page === 'spam-room' && activeConversation && <ChatRoomPage convo={activeConversation} messages={messages} back={() => setPage('spam-detail')} spamMode={true} onSend={handleSend} />}{notice ? <div className="toast" onAnimationEnd={() => setNotice('')}>{notice}</div> : null}<NewChatModal open={composerOpen} onClose={() => { setComposerOpen(false); setComposeWarning(false); }} onSubmit={handleComposerSubmit} knownExists={composeWarning === false} warning={composeWarning} sending={sending} /></div>;
}

